on:
  pull_request_target:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  approve: # First step
    runs-on: ubuntu-latest
    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.
      
  build-forks: # Second step for forks
    runs-on: ubuntu-latest
    needs: [approve] # Require the first step to finish
    environment:
      name: Integrate Pull Request # Our dummy environment
    steps:
    - name: Test
      run: echo Test Complete
      
  build-sources: # Second step for sources
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo Test Complete

  # Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: [build-forks, build-sources] # Run this job after the other jobs
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build & Deploy to GitHub Pages
      uses: helaili/jekyll-action@2.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}